# Generated by Django 3.2.16 on 2024-03-18 18:22

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('salary_min', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Минимальная з/п')),
                ('salary_max', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Максимальная з/п')),
            ],
        ),
        migrations.CreateModel(
            name='Citizenship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Гражданство',
                'verbose_name_plural': 'Гражданство',
            },
        ),
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Требование',
                'verbose_name_plural': 'Требования',
            },
        ),
        migrations.CreateModel(
            name='Duty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Обязанность',
                'verbose_name_plural': 'Обязанности',
            },
        ),
        migrations.CreateModel(
            name='Other',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Прочие',
                'verbose_name_plural': 'Прочие',
            },
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Профессия',
                'verbose_name_plural': 'Профессии',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Навык',
                'verbose_name_plural': 'Навыки',
            },
        ),
        migrations.CreateModel(
            name='ApplicationSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.application', verbose_name='Заявка')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.skill', verbose_name='Навыки')),
            ],
            options={
                'verbose_name': 'ЗаявкаНавыки',
                'verbose_name_plural': 'ЗаявкаНавыки',
            },
        ),
        migrations.CreateModel(
            name='ApplicationProfession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.application', verbose_name='Заявка')),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professions_id', to='app.profession', verbose_name='Профессия')),
            ],
            options={
                'verbose_name': 'ЗаявкаПрофессия',
                'verbose_name_plural': 'ЗаявкаПрофессия',
            },
        ),
        migrations.CreateModel(
            name='ApplicationOther',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.application', verbose_name='Заявка')),
                ('other', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.other', verbose_name='Прочие')),
            ],
            options={
                'verbose_name': 'ЗаявкаПрочие',
                'verbose_name_plural': 'ЗаявкаПрочие',
            },
        ),
        migrations.CreateModel(
            name='ApplicationDuty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.application', verbose_name='Заявка')),
                ('duty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.duty', verbose_name='Обязанность')),
            ],
            options={
                'verbose_name': 'ЗаявкаОбязанности',
                'verbose_name_plural': 'ЗаявкаОбязанности',
            },
        ),
        migrations.CreateModel(
            name='ApplicationClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.application', verbose_name='Заявка')),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.claim', verbose_name='Требования')),
            ],
            options={
                'verbose_name': 'ЗаявкаТребования',
                'verbose_name_plural': 'ЗаявкаТребования',
            },
        ),
        migrations.CreateModel(
            name='ApplicationCitizenship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.application', verbose_name='Заявка')),
                ('сitizenship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.citizenship', verbose_name='Прочие')),
            ],
            options={
                'verbose_name': 'ЗаявкаГражданство',
                'verbose_name_plural': 'ЗаявкаГражданство',
            },
        ),
        migrations.AddField(
            model_name='application',
            name='citizenship_id',
            field=models.ManyToManyField(related_name='citizenship_application', through='app.ApplicationCitizenship', to='app.Citizenship', verbose_name='Гражданство'),
        ),
        migrations.AddField(
            model_name='application',
            name='description_claims',
            field=models.ManyToManyField(related_name='claims_application', through='app.ApplicationClaim', to='app.Claim', verbose_name='Описание требований'),
        ),
        migrations.AddField(
            model_name='application',
            name='description_duties',
            field=models.ManyToManyField(related_name='duties_application', through='app.ApplicationDuty', to='app.Duty', verbose_name='описание обязанностей'),
        ),
        migrations.AddField(
            model_name='application',
            name='description_other',
            field=models.ManyToManyField(related_name='other_application', through='app.ApplicationOther', to='app.Other', verbose_name='Прочие описание'),
        ),
        migrations.AddField(
            model_name='application',
            name='description_skills',
            field=models.ManyToManyField(related_name='skills_application', through='app.ApplicationSkill', to='app.Skill', verbose_name='Описание навыков'),
        ),
        migrations.AddField(
            model_name='application',
            name='profession_id',
            field=models.ManyToManyField(related_name='profession_application', through='app.ApplicationProfession', to='app.Profession', verbose_name='Профессия'),
        ),
    ]
