# Generated by Django 3.2 on 2024-03-16 22:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Название вакансии')),
                ('salary', models.PositiveIntegerField()),
                ('created', models.DateField(auto_now_add=True)),
                ('employer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=256, unique=True, verbose_name='Название профессии')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=256, unique=True, verbose_name='Название профессии')),
            ],
        ),
        migrations.CreateModel(
            name='SkillApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.application')),
                ('skill_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.skill')),
            ],
        ),
        migrations.AddField(
            model_name='application',
            name='profession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.profession'),
        ),
        migrations.AddField(
            model_name='application',
            name='skills',
            field=models.ManyToManyField(through='app.SkillApplication', to='app.Skill'),
        ),
    ]
