# Generated by Django 3.2 on 2024-03-22 11:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата публикации')),
                ('mission', models.BooleanField(verbose_name='Командировки')),
                ('bonus', models.BooleanField(verbose_name='Бонусы от работодателя')),
                ('salary_min', models.PositiveBigIntegerField(verbose_name='Минимальная зарплата')),
                ('salary_max', models.PositiveBigIntegerField(verbose_name='Максимальня зараплта')),
                ('responsibilities', models.TextField(verbose_name='Обязанности сотрудника')),
                ('other_requirements', models.TextField(verbose_name='Дополнительные требования')),
                ('candidates_count', models.PositiveIntegerField(verbose_name='Количество кандидатов')),
                ('recruiter_count', models.PositiveIntegerField(verbose_name='Количество рекрутеров')),
                ('award', models.PositiveIntegerField(verbose_name='Вознаграждение рекрутера')),
                ('name', models.TextField(default='Новая заявка', max_length=256, verbose_name='Название вакансии/заявки')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ('date',),
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Образование',
                'verbose_name_plural': 'Варианты образования',
            },
        ),
        migrations.CreateModel(
            name='Expectations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Задача рекрутера',
                'verbose_name_plural': 'Задачи рекрутера',
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Опыт работы в годах',
                'verbose_name_plural': 'Варианты опыта работы в годах',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Знание языка',
                'verbose_name_plural': 'Знание языков',
            },
        ),
        migrations.CreateModel(
            name='LanguageLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Уровень языка',
                'verbose_name_plural': 'Уровни языка',
            },
        ),
        migrations.CreateModel(
            name='Occupation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тип занятости',
                'verbose_name_plural': 'Типы занятости',
            },
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Вариант выплаты рекрутеру',
                'verbose_name_plural': 'Варианты выплат рекрутеру',
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Вариант оформления',
                'verbose_name_plural': 'Варианты оформления',
            },
        ),
        migrations.CreateModel(
            name='Salaryrecomend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary_recomend', models.PositiveIntegerField(verbose_name='Рекомендуемая зарплата')),
            ],
            options={
                'verbose_name': 'Рекомендуемая зарплата',
                'verbose_name_plural': 'Рекомендуемые зарплаты',
            },
        ),
        migrations.CreateModel(
            name='SalaryrecomendTown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary_recomend', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.salaryrecomend', verbose_name='Рекомендуемые зарплаты по специальности')),
            ],
            options={
                'verbose_name': 'Рекомендуемые зарплаты по специальностям в городах',
                'verbose_name_plural': 'Рекомендуемые зарплаты по специальностям в городах',
                'ordering': ('specialization_id',),
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'График работы',
                'verbose_name_plural': 'Варианты графика работы',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Навык',
                'verbose_name_plural': 'Ключевые навыки',
            },
        ),
        migrations.CreateModel(
            name='SkillSpecialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.skill', verbose_name='Навык')),
            ],
            options={
                'verbose_name': 'Специальность-Навык',
                'verbose_name_plural': 'Специальности-Навыки',
                'ordering': ('specialization_id',),
            },
        ),
        migrations.CreateModel(
            name='Towns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
            },
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True, verbose_name='Название')),
                ('salary_recomend', models.ManyToManyField(through='app.SalaryrecomendTown', to='app.Salaryrecomend', verbose_name='Зарплаты по специальностям в городах')),
                ('skills_recomend', models.ManyToManyField(through='app.SkillSpecialization', to='app.Skill', verbose_name='Навыки специальности')),
            ],
            options={
                'verbose_name': 'Специальность',
                'verbose_name_plural': 'Специальности',
            },
        ),
        migrations.AddField(
            model_name='skillspecialization',
            name='specialization_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.specialization', verbose_name='Специальность'),
        ),
        migrations.CreateModel(
            name='SkillApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.application', verbose_name='Заявка')),
                ('skill_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.skill', verbose_name='Навык')),
            ],
            options={
                'verbose_name': 'Заявка-Навык',
                'verbose_name_plural': 'Заявки-Навыки',
                'ordering': ('application_id',),
            },
        ),
        migrations.CreateModel(
            name='ScheduleApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Schedule_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.schedule', verbose_name='График')),
                ('application_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.application', verbose_name='Заявка')),
            ],
            options={
                'verbose_name': 'Заявка-График',
                'verbose_name_plural': 'Заявка-Графики',
                'ordering': ('application_id',),
            },
        ),
        migrations.AddField(
            model_name='salaryrecomendtown',
            name='specialization_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.specialization', verbose_name='Специльность'),
        ),
        migrations.AddField(
            model_name='salaryrecomendtown',
            name='town_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.towns', verbose_name='Город'),
        ),
        migrations.CreateModel(
            name='RegistrationApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.application', verbose_name='Заявка')),
                ('registration_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.registration', verbose_name='Оформление')),
            ],
            options={
                'verbose_name': 'Заявка-Оформление',
                'verbose_name_plural': 'Заявка-Оформление',
                'ordering': ('application_id',),
            },
        ),
        migrations.CreateModel(
            name='OccupationApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.application', verbose_name='Заявка')),
                ('occupation_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.occupation', verbose_name='ТипЗанятости')),
            ],
            options={
                'verbose_name': 'Заявка-ТипЗанятости',
                'verbose_name_plural': 'Заявка-ТипыЗанятости',
                'ordering': ('application_id',),
            },
        ),
        migrations.CreateModel(
            name='LanguageApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.application', verbose_name='Заявка')),
                ('language_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.language', verbose_name='Язык')),
                ('language_level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.languagelevel', verbose_name='Уровень языка')),
            ],
            options={
                'verbose_name': 'Заявка-Язык',
                'verbose_name_plural': 'Заявки-Языки',
                'ordering': ('application_id',),
            },
        ),
        migrations.CreateModel(
            name='ExpectationsApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.application', verbose_name='Заявка')),
                ('expectations_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.expectations', verbose_name='ЗадачаРекрутера')),
            ],
            options={
                'verbose_name': 'Заявка-ЗадачаРекрутера',
                'verbose_name_plural': 'Заявка-ЗадачиРекрутера',
                'ordering': ('application_id',),
            },
        ),
        migrations.AddField(
            model_name='application',
            name='education',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.education', verbose_name='Образование'),
        ),
        migrations.AddField(
            model_name='application',
            name='employer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='application',
            name='expectations',
            field=models.ManyToManyField(through='app.ExpectationsApplication', to='app.Expectations', verbose_name='Задачи рекрутера'),
        ),
        migrations.AddField(
            model_name='application',
            name='experience',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.experience', verbose_name='Опыт работы'),
        ),
        migrations.AddField(
            model_name='application',
            name='languages',
            field=models.ManyToManyField(through='app.LanguageApplication', to='app.Language', verbose_name='Знание языков'),
        ),
        migrations.AddField(
            model_name='application',
            name='occupation',
            field=models.ManyToManyField(through='app.OccupationApplication', to='app.Occupation', verbose_name='Тип занятости'),
        ),
        migrations.AddField(
            model_name='application',
            name='payments',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.payments', verbose_name='Варианты выплат рекрутеру'),
        ),
        migrations.AddField(
            model_name='application',
            name='registration',
            field=models.ManyToManyField(through='app.RegistrationApplication', to='app.Registration', verbose_name='Варианты оформления'),
        ),
        migrations.AddField(
            model_name='application',
            name='skills',
            field=models.ManyToManyField(through='app.SkillApplication', to='app.Skill', verbose_name='Навыки'),
        ),
        migrations.AddField(
            model_name='application',
            name='specialization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.specialization', verbose_name='Специальность'),
        ),
        migrations.AddField(
            model_name='application',
            name='timetable',
            field=models.ManyToManyField(through='app.ScheduleApplication', to='app.Schedule', verbose_name='График работы'),
        ),
        migrations.AddField(
            model_name='application',
            name='towns',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.towns', verbose_name='Города'),
        ),
    ]
