# Generated by Django 3.2 on 2024-03-23 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salaryrecomendtown',
            name='author',
        ),
    ]
