# Generated by Django 3.2 on 2024-03-19 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='education',
            options={'verbose_name': 'Образование', 'verbose_name_plural': 'Варианты образования'},
        ),
        migrations.AlterModelOptions(
            name='expectations',
            options={'verbose_name': 'Задача рекрутера', 'verbose_name_plural': 'Задачи рекрутера'},
        ),
        migrations.AlterModelOptions(
            name='experience',
            options={'verbose_name': 'Опыт работы в годах', 'verbose_name_plural': 'Варианты опыта работы в годах'},
        ),
        migrations.AlterModelOptions(
            name='language',
            options={'verbose_name': 'Знание языка', 'verbose_name_plural': 'Знание языков'},
        ),
        migrations.AlterModelOptions(
            name='languagelevel',
            options={'verbose_name': 'Уровень языка', 'verbose_name_plural': 'Уровни языка'},
        ),
        migrations.AlterModelOptions(
            name='occupation',
            options={'verbose_name': 'Тип занятости', 'verbose_name_plural': 'Типы занятости'},
        ),
        migrations.AlterModelOptions(
            name='payments',
            options={'verbose_name': 'Вариант выплаты рекрутеру', 'verbose_name_plural': 'Варианты выплат рекрутеру'},
        ),
        migrations.AlterModelOptions(
            name='registration',
            options={'verbose_name': 'Вариант оформления', 'verbose_name_plural': 'Варианты оформления'},
        ),
        migrations.AlterModelOptions(
            name='schedule',
            options={'verbose_name': 'График работы', 'verbose_name_plural': 'Варианты графика работы'},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'verbose_name': 'Навык', 'verbose_name_plural': 'Ключевые навыки'},
        ),
        migrations.AlterModelOptions(
            name='specialization',
            options={'verbose_name': 'Специальность', 'verbose_name_plural': 'Специальности'},
        ),
        migrations.AlterModelOptions(
            name='towns',
            options={'verbose_name': 'Город', 'verbose_name_plural': 'Города'},
        ),
        migrations.AlterField(
            model_name='application',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='application',
            name='education',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.education', verbose_name='Образование'),
        ),
        migrations.AlterField(
            model_name='application',
            name='expectations',
            field=models.ManyToManyField(through='app.ExpectationsApplication', to='app.Expectations', verbose_name='Задачи рекрутера'),
        ),
        migrations.AlterField(
            model_name='application',
            name='experience',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.experience', verbose_name='Опыт работы'),
        ),
        migrations.AlterField(
            model_name='application',
            name='languages',
            field=models.ManyToManyField(through='app.LanguageApplication', to='app.Language', verbose_name='Знание языков'),
        ),
        migrations.AlterField(
            model_name='application',
            name='occupation',
            field=models.ManyToManyField(through='app.OccupationApplication', to='app.Occupation', verbose_name='Тип занятости'),
        ),
        migrations.AlterField(
            model_name='application',
            name='payments',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.payments', verbose_name='Варианты выплат рекрутеру'),
        ),
        migrations.AlterField(
            model_name='application',
            name='registration',
            field=models.ManyToManyField(through='app.RegistrationApplication', to='app.Registration', verbose_name='Варианты оформления'),
        ),
        migrations.AlterField(
            model_name='application',
            name='skills',
            field=models.ManyToManyField(through='app.SkillApplication', to='app.Skill', verbose_name='Навыки'),
        ),
        migrations.AlterField(
            model_name='application',
            name='specialization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.specialization', verbose_name='Специальность'),
        ),
        migrations.AlterField(
            model_name='application',
            name='timetable',
            field=models.ManyToManyField(through='app.ScheduleApplication', to='app.Schedule', verbose_name='График работы'),
        ),
        migrations.AlterField(
            model_name='application',
            name='towns',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.towns', verbose_name='Города'),
        ),
        migrations.AlterField(
            model_name='education',
            name='name',
            field=models.CharField(max_length=256, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='expectations',
            name='name',
            field=models.CharField(max_length=256, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='name',
            field=models.CharField(max_length=256, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(max_length=256, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='languagelevel',
            name='name',
            field=models.CharField(max_length=256, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='occupation',
            name='name',
            field=models.CharField(max_length=256, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='payments',
            name='name',
            field=models.CharField(max_length=256, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='name',
            field=models.CharField(max_length=256, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='name',
            field=models.CharField(max_length=256, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(max_length=256, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='specialization',
            name='name',
            field=models.CharField(max_length=256, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='towns',
            name='name',
            field=models.CharField(max_length=256, unique=True, verbose_name='Название'),
        ),
    ]
