# Generated by Django 3.2 on 2024-03-22 11:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='bonus',
            field=models.BooleanField(null=True, verbose_name='Бонусы от работодателя'),
        ),
        migrations.AlterField(
            model_name='application',
            name='employer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Работодатель'),
        ),
        migrations.AlterField(
            model_name='application',
            name='mission',
            field=models.BooleanField(null=True, verbose_name='Командировки'),
        ),
        migrations.AlterField(
            model_name='application',
            name='name',
            field=models.CharField(default='Новая заявка', max_length=256, verbose_name='Название вакансии/заявки'),
        ),
        migrations.AlterField(
            model_name='application',
            name='other_requirements',
            field=models.TextField(null=True, verbose_name='Дополнительные требования'),
        ),
        migrations.AlterField(
            model_name='application',
            name='salary_max',
            field=models.PositiveBigIntegerField(null=True, verbose_name='Максимальня зараплта'),
        ),
        migrations.AlterField(
            model_name='application',
            name='salary_min',
            field=models.PositiveBigIntegerField(null=True, verbose_name='Минимальная зарплата'),
        ),
    ]
