# Generated by Django 3.2 on 2024-03-20 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ('date',), 'verbose_name': 'Заявка', 'verbose_name_plural': 'Заявки'},
        ),
        migrations.AlterModelOptions(
            name='education',
            options={'ordering': ('-name',), 'verbose_name': 'Образование', 'verbose_name_plural': 'Варианты образования'},
        ),
        migrations.AlterModelOptions(
            name='expectations',
            options={'ordering': ('-name',), 'verbose_name': 'Задача рекрутера', 'verbose_name_plural': 'Задачи  рекрутера'},
        ),
        migrations.AlterModelOptions(
            name='experience',
            options={'ordering': ('-name',), 'verbose_name': 'Опыт работы в годах', 'verbose_name_plural': 'Варианты опыта работы в годах'},
        ),
        migrations.AlterModelOptions(
            name='language',
            options={'ordering': ('-name',), 'verbose_name': 'Знание языка', 'verbose_name_plural': 'Знание языков'},
        ),
        migrations.AlterModelOptions(
            name='languagelevel',
            options={'ordering': ('-name',), 'verbose_name': 'Уровень языка', 'verbose_name_plural': 'Уровни языка'},
        ),
        migrations.AlterModelOptions(
            name='occupation',
            options={'ordering': ('-name',), 'verbose_name': 'Тип  занятости', 'verbose_name_plural': 'Типы занятости'},
        ),
        migrations.AlterModelOptions(
            name='payments',
            options={'ordering': ('-name',), 'verbose_name': 'Вариант выплаты рекрутеру', 'verbose_name_plural': 'Варианты выплат рекрутеру'},
        ),
        migrations.AlterModelOptions(
            name='registration',
            options={'ordering': ('-name',), 'verbose_name': 'Варинт оформления', 'verbose_name_plural': 'Варинты оформления'},
        ),
        migrations.AlterModelOptions(
            name='schedule',
            options={'ordering': ('-name',), 'verbose_name': 'График работы', 'verbose_name_plural': 'Варианты графика работы'},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ('-name',), 'verbose_name': 'Навык', 'verbose_name_plural': 'Ключевые навыки'},
        ),
        migrations.AlterModelOptions(
            name='skillapplication',
            options={'ordering': ('application_id',), 'verbose_name': 'Заявка-Навык', 'verbose_name_plural': 'Заявки-Навыки'},
        ),
        migrations.AlterModelOptions(
            name='specialization',
            options={'ordering': ('-name',), 'verbose_name': 'Специальность', 'verbose_name_plural': 'Специальности'},
        ),
        migrations.AlterModelOptions(
            name='towns',
            options={'ordering': ('-name',), 'verbose_name': 'Город', 'verbose_name_plural': 'Города'},
        ),
        migrations.AlterField(
            model_name='skillapplication',
            name='application_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.application', verbose_name='Заявка'),
        ),
        migrations.AlterField(
            model_name='skillapplication',
            name='skill_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.skill', verbose_name='Навык'),
        ),
    ]
