# Generated by Django 3.2 on 2024-03-20 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20240319_2141'),
        ('app', '0002_auto_20240320_1349'),
    ]

    operations = [
    ]
