# Generated by Django 3.2 on 2024-03-21 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_merge_0002_auto_20240319_2141_0002_auto_20240320_1349'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expectationsapplication',
            options={'ordering': ('application_id',), 'verbose_name': 'Заявка-ЗадачаРекрутера', 'verbose_name_plural': 'Заявка-ЗадачиРекрутера'},
        ),
        migrations.AlterModelOptions(
            name='languageapplication',
            options={'ordering': ('application_id',), 'verbose_name': 'Заявка-Язык', 'verbose_name_plural': 'Заявки-Языки'},
        ),
        migrations.AlterModelOptions(
            name='occupationapplication',
            options={'ordering': ('application_id',), 'verbose_name': 'Заявка-ТипЗанятости', 'verbose_name_plural': 'Заявка-ТипыЗанятости'},
        ),
        migrations.AlterModelOptions(
            name='registrationapplication',
            options={'ordering': ('application_id',), 'verbose_name': 'Заявка-Оформление', 'verbose_name_plural': 'Заявка-Оформление'},
        ),
        migrations.AlterModelOptions(
            name='scheduleapplication',
            options={'ordering': ('application_id',), 'verbose_name': 'Заявка-График', 'verbose_name_plural': 'Заявка-Графики'},
        ),
        migrations.AlterField(
            model_name='application',
            name='award',
            field=models.PositiveIntegerField(verbose_name='Вознаграждение рекрутера'),
        ),
        migrations.AlterField(
            model_name='application',
            name='bonus',
            field=models.BooleanField(verbose_name='Бонусы от\xa0работодателя'),
        ),
        migrations.AlterField(
            model_name='application',
            name='countCandidates',
            field=models.PositiveIntegerField(verbose_name='Количество кандидатов'),
        ),
        migrations.AlterField(
            model_name='application',
            name='countRecruiter',
            field=models.PositiveIntegerField(verbose_name='Количество рекрутеров'),
        ),
        migrations.AlterField(
            model_name='application',
            name='mission',
            field=models.BooleanField(verbose_name='Командировки'),
        ),
        migrations.AlterField(
            model_name='application',
            name='salary',
            field=models.PositiveIntegerField(verbose_name='Зарплата'),
        ),
        migrations.AlterField(
            model_name='expectationsapplication',
            name='application_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.application', verbose_name='Заявка'),
        ),
        migrations.AlterField(
            model_name='expectationsapplication',
            name='expectations_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.expectations', verbose_name='ЗадачаРекрутера'),
        ),
        migrations.AlterField(
            model_name='languageapplication',
            name='application_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.application', verbose_name='Заявка'),
        ),
        migrations.AlterField(
            model_name='languageapplication',
            name='language_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.language', verbose_name='Язык'),
        ),
        migrations.AlterField(
            model_name='languageapplication',
            name='language_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.languagelevel', verbose_name='Уровень языка'),
        ),
        migrations.AlterField(
            model_name='occupationapplication',
            name='application_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.application', verbose_name='Заявка'),
        ),
        migrations.AlterField(
            model_name='occupationapplication',
            name='occupation_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.occupation', verbose_name='ТипЗанятости'),
        ),
        migrations.AlterField(
            model_name='registrationapplication',
            name='application_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.application', verbose_name='Заявка'),
        ),
        migrations.AlterField(
            model_name='registrationapplication',
            name='registration_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.registration', verbose_name='Оформление'),
        ),
        migrations.AlterField(
            model_name='scheduleapplication',
            name='Schedule_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.schedule', verbose_name='График'),
        ),
        migrations.AlterField(
            model_name='scheduleapplication',
            name='application_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.application', verbose_name='Заявка'),
        ),
        migrations.CreateModel(
            name='SkillSpecialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.skill', verbose_name='Навык')),
                ('specialization_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.specialization', verbose_name='Специальность')),
            ],
            options={
                'verbose_name': 'Специальность-Навык',
                'verbose_name_plural': 'Специальности-Навыки',
                'ordering': ('specialization_id',),
            },
        ),
    ]
