# Generated by Django 3.2 on 2024-03-21 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20240322_0117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialization',
            name='salary_recomend',
            field=models.PositiveIntegerField(verbose_name='Рекомендуемая зарплата'),
        ),
    ]
