version: '3.8'

services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - db_value://var/lib/postgresql/data/
    env_file:
      - ./.env
  backend:
    image: "${DOCKER_USERNAME}/hrspace_backend:latest"
    restart: always
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    depends_on:
      - db
    env_file:
      - ./.env
  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      #- /etc/letsencrypt/live/hrspace.servemp3.com/:/etc/letsencrypt/live/hrspace.servemp3.com/
      - /etc/letsencrypt/live/hrspace.servemp3.com/fullchain.pem:/etc/ssl/certs/fullchain.pem
      - /etc/letsencrypt/live/hrspace.servemp3.com/privkey.pem:/etc/ssl/private/privkey.pem
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - backend

volumes:
  db_value:
  static_value:
  media_value: